[package]
name = "timeit-ru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.144"

[profile.release]
opt-level = "z"
strip = true
lto = true
